/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import com.Dao.FuncionariosDaoImp;
import com.connection.Conexion;
import com.models.Funcionariomodel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author traba
 */
public class crud extends javax.swing.JFrame {

    /**
     * Creates new form funcionarios
     */
    public crud() {
        initComponents();
        verdatos();
        llenarcombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtcedula = new javax.swing.JTextField();
        guardar = new javax.swing.JButton();
        txtnombre = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listado = new javax.swing.JTable();
        update = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        nuevo = new javax.swing.JButton();
        combotipoid = new javax.swing.JComboBox<>();
        txtdireccion = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        txtfechanac = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtestadocivil = new javax.swing.JComboBox<>();
        txtsexo = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 204, 255));
        jLabel1.setText("Registro de funcionarios");

        txtid.setEditable(false);
        txtid.setToolTipText("");
        txtid.setName("txtid"); // NOI18N
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        txtcedula.setName("txtcedula"); // NOI18N
        txtcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcedulaActionPerformed(evt);
            }
        });

        guardar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        guardar.setText("guardar");
        guardar.setEnabled(false);
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        txtnombre.setToolTipText("");
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });

        listado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "numero_identificacion", "tipo_id", "nombre", "apellido", "sexo", "telefono", "direccion", "fecha_nacimiento", "Estado_civil", "fecha_creacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        listado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listado);

        update.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        update.setText("update");
        update.setEnabled(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        eliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        eliminar.setForeground(new java.awt.Color(255, 0, 51));
        eliminar.setText("delete");
        eliminar.setEnabled(false);
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        nuevo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nuevo.setText("Nuevo");
        nuevo.setActionCommand("");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });

        combotipoid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo documento" }));

        txttelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefonoActionPerformed(evt);
            }
        });

        txtfechanac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfechanacActionPerformed(evt);
            }
        });

        jLabel2.setText("N. identificacion");

        jLabel3.setText("Id");

        jLabel4.setText("nombres");

        jLabel5.setText("apellidos");

        jLabel6.setText("direccion");

        jLabel7.setText("telefono");

        jLabel8.setText("sexo");

        jLabel9.setText("fecha nacimiento");

        jLabel12.setText("Estado civil");

        txtestadocivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estado civil" }));

        txtsexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sexo", "M", "F", "O" }));
        txtsexo.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(144, 144, 144)
                                        .addComponent(nuevo)
                                        .addGap(18, 18, 18)
                                        .addComponent(guardar)
                                        .addGap(11, 11, 11)
                                        .addComponent(update)
                                        .addGap(33, 33, 33)
                                        .addComponent(eliminar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtcedula)
                                            .addComponent(txtnombre)
                                            .addComponent(txtapellido)
                                            .addComponent(combotipoid, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(155, 155, 155)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel8))
                                        .addGap(15, 15, 15)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtfechanac, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtestadocivil, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtsexo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1392, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(424, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(combotipoid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel4)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel5))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfechanac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtestadocivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel12)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(guardar)
                        .addComponent(update)
                        .addComponent(eliminar)
                        .addComponent(nuevo))
                    .addComponent(jLabel7))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcedulaActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
FuncionariosDaoImp funcionario_dao = new FuncionariosDaoImp();
Funcionariomodel funcionario =new Funcionariomodel();


int id=0; // Integer.parseInt(txtid.getText());
String cedula= txtcedula.getText();
String nombre= txtnombre.getText();
String apellido= txtapellido.getText();

String sex= txtsexo.getSelectedItem().toString();
//JOptionPane.showMessageDialog(null,sex);

String dir= txtdireccion.getText();
String tel= txttelefono.getText();
String fen= txtfechanac.getText();
int est= txtestadocivil.getSelectedIndex();
int tip= combotipoid.getSelectedIndex();



funcionario.setId(id);
funcionario.setNumeroIdentificacion(cedula);
funcionario.setNombre(nombre);
funcionario.setApellido(apellido);

funcionario.setSexo(sex);
funcionario.setDireccion(dir);
funcionario.setTelefono(tel);
funcionario.setFechaNacimiento(fen);
funcionario.setEstadoCivil(est);
funcionario.setTipoIdentificacion(tip);


funcionario_dao.registrar(funcionario);
verdatos();
JOptionPane.showMessageDialog(null,"registro guardado");



    }//GEN-LAST:event_guardarActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        FuncionariosDaoImp funcionario_dao = new FuncionariosDaoImp();
Funcionariomodel funcionario =new Funcionariomodel();

int id= Integer.parseInt(txtid.getText());
String cedula= txtcedula.getText();
String nombre= txtnombre.getText();
String apellido= txtapellido.getText();

String sex= txtsexo.getSelectedItem().toString();

String dir= txtdireccion.getText();
String tel= txttelefono.getText();
String fen= txtfechanac.getText();
int est= txtestadocivil.getSelectedIndex();
int tip= combotipoid.getSelectedIndex();



funcionario.setId(id);
funcionario.setNumeroIdentificacion(cedula);
funcionario.setNombre(nombre);
funcionario.setApellido(apellido);

funcionario.setSexo(sex);
funcionario.setDireccion(dir);
funcionario.setTelefono(tel);
funcionario.setFechaNacimiento(fen);
funcionario.setEstadoCivil(est);
funcionario.setTipoIdentificacion(tip);

//JOptionPane.showMessageDialog(null,funcionario.getId());

funcionario_dao.actualizar(funcionario);
verdatos();
JOptionPane.showMessageDialog(null,"registro actualizado");

    }//GEN-LAST:event_updateActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        
          FuncionariosDaoImp funcionario_dao = new FuncionariosDaoImp();
Funcionariomodel funcionario =new Funcionariomodel();

int fila= listado.getSelectedRow();
String dato=listado.getValueAt(fila, 0).toString();
//JOptionPane.showMessageDialog(null,dato);

//String id= txtid.getText();
int id= Integer.parseInt(dato);
funcionario.setId(id);

funcionario_dao.eliminar(funcionario);
verdatos();
JOptionPane.showMessageDialog(null,"registro eliminado");


    }//GEN-LAST:event_eliminarActionPerformed

    private void listadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadoMouseClicked
        // TODO add your handling code here:
        int fila= listado.getSelectedRow();
String did=listado.getValueAt(fila, 0).toString();
String dni=listado.getValueAt(fila, 1).toString();
String tipoid=listado.getValueAt(fila, 2).toString();
String dnombre=listado.getValueAt(fila, 3).toString();
String dapellido=listado.getValueAt(fila, 4).toString();
String dsex=listado.getValueAt(fila, 5).toString();
String dir=listado.getValueAt(fila, 6).toString();
String dtel=listado.getValueAt(fila, 7).toString();

String dfna=listado.getValueAt(fila, 8).toString();
//String dfcre=listado.getValueAt(fila, 9).toString();
//String dfact=listado.getValueAt(fila, 10).toString();
String dest=listado.getValueAt(fila, 9).toString();

Integer numero = Integer.parseInt(dest);
Integer tipoid1 = Integer.parseInt(tipoid);
txtid.setText(did);
txtcedula.setText(dni);
txtnombre.setText(dnombre);
txtapellido.setText(dapellido);

txtdireccion.setText(dir);
txttelefono.setText(dtel);

txtsexo.setSelectedItem(dsex);

txtfechanac.setText(dfna);
//txtfechacre.setText(dfcre);
//txtfechaapt.setText(dfact);
//JOptionPane.showMessageDialog(null,dest);

txtestadocivil.setSelectedIndex(numero);
combotipoid.setSelectedIndex(tipoid1);


 update.setEnabled(true);
  eliminar.setEnabled(true);
  txtid.setEnabled(false);

        
    }//GEN-LAST:event_listadoMouseClicked

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        // TODO add your handling code here:
        verdatos();
        guardar.setEnabled(true);
        txtid.setEnabled(true);
        update.setEnabled(false);
  eliminar.setEnabled(false);
        
    }//GEN-LAST:event_nuevoActionPerformed

    private void txttelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefonoActionPerformed

    private void txtfechanacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfechanacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfechanacActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crud().setVisible(true);
            }
        });
    }
    
    private void llenarcombo() {
        Connection con;
con=Conexion.conectar();
try{

PreparedStatement seleccion  =con.prepareStatement("SELECT * FROM tipos_identificacion");
            ResultSet consulta = seleccion.executeQuery();
      while(consulta.next()){
       
         combotipoid.addItem(consulta.getString(2));
          
      }
      
   
      
            
            

}catch (SQLException ex) {
            Logger.getLogger(crud.class.getName()).log(Level.SEVERE, null, ex);
        }


        try {
             PreparedStatement seleccion1  =con.prepareStatement("SELECT * FROM estados_civil");
            ResultSet consulta1 = seleccion1.executeQuery();
      while(consulta1.next()){
       
         txtestadocivil.addItem(consulta1.getString(2));
          
      }  
        } catch (Exception e) {
        }
     
        
    
    }
    
    
    private void verdatos(){
       DefaultTableModel modelo = new DefaultTableModel();
listado.setModel(modelo);
Connection con;
con=Conexion.conectar();

txtid.setText("");
txtcedula.setText("");
txtnombre.setText("");
txtapellido.setText("");
txtdireccion.setText("");
txttelefono.setText("");
txtfechanac.setText("");
//txtsexo.setText("");
txtsexo.setSelectedIndex(0);
txtestadocivil.setSelectedIndex(0);
combotipoid.setSelectedIndex(0);


                        
        try {
            PreparedStatement seleccion  =con.prepareStatement("SELECT * FROM funcionarios");
            ResultSet consulta = seleccion.executeQuery();
            
            
            modelo.addColumn("id");
             modelo.addColumn("Numero_identificacion");
            modelo.addColumn("tipo_identificacion");
            modelo.addColumn("nombres");
            modelo.addColumn("apellidos");
             modelo.addColumn("sexo");
              modelo.addColumn("direccion");
               modelo.addColumn("telefono");
                modelo.addColumn("fecha_nacimiento");
               //  modelo.addColumn("fecha_creacion");
                //  modelo.addColumn("fecha_actualizacion");
                   modelo.addColumn("estado_civil");
                  
            
            int a=0;
             String [] registros = new String[10];
        while(consulta.next()){
            
            a++;
            registros[0] = consulta.getString(1);
            
                    
                    
            registros[1] = consulta.getString(2);
           registros[2] =consulta.getString(9);
            registros[3] = consulta.getString(3);
             registros[4] = consulta.getString(4);
              registros[5] = consulta.getString(5);
               registros[6] = consulta.getString(6);
                registros[7] = consulta.getString(7);
                 registros[8] = consulta.getString(8);
                  registros[9] = consulta.getString(9);
                  // registros[10] = consulta.getString(11);
                   // registros[11] = consulta.getString(12);
                    
                  
            
            modelo.addRow(registros);   
             } 
        }catch (SQLException ex) {
            Logger.getLogger(crud.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combotipoid;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton guardar;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listado;
    private javax.swing.JButton nuevo;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JComboBox<String> txtestadocivil;
    private javax.swing.JTextField txtfechanac;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JComboBox<String> txtsexo;
    private javax.swing.JTextField txttelefono;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
